name: autofix.ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install
        run: pnpm install --no-frozen-lockfile

      - name: Lint and fix
        run: pnpm run lint:fix

      - uses: autofix-ci/action@8caa572fd27b0019a65e4c695447089c8d3138b9
